app = "mailsender-app01"
primary_region = "fra"  # Франкфурт, можно заменить на другой регион

[build]
  builder = "heroku/buildpacks:20"

[env]
  DJANGO_SETTINGS_MODULE = "mailsender.settings"
  SECRET_KEY = "ЗДЕСЬ_БУДЕТ_ПОДСТАВЛЕН_СЕКРЕТ_ИЗ_SECRETS"
  DEBUG = "False"
  ALLOWED_HOSTS = "mailsender-app01.fly.dev"
  EMAIL_HOST = "smtp.yandex.ru"
  EMAIL_PORT = "587"
  EMAIL_HOST_USER = "eugeneyasakov@yandex.ru"
  EMAIL_HOST_PASSWORD = "ТОЖЕ_БУДЕТ_СЕКРЕТ"
  EMAIL_USE_TLS = "True"
  DEFAULT_FROM_EMAIL = "eugeneyasakov@yandex.ru"

[[services]]
  internal_port = 8000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    interval = "10s"
    timeout = "2s"
    grace_period = "10s"
    restart_limit = 5
