
name: CI & CD

on:
  push:
    branches: [develop, main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8

      - name: Lint code
        run: flake8 .

      - name: Run migrations
        run: python manage.py migrate

      - name: Run tests
        env:
          SECRET_KEY: testsecret
          DEBUG: "True"
          ALLOWED_HOSTS: 127.0.0.1,localhost
        run: python manage.py test

  docker-build:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - uses: actions/checkout@v3

      - name: Build Docker image
        run: docker build -t mailsender .

      - name: Save Docker image as tar
        run: docker save mailsender > mailsender.tar

      - name: Upload Docker image tar as artifact
        uses: actions/upload-artifact@v3
        with:
          name: mailsender-image
          path: mailsender.tar

  deploy:
    runs-on: ubuntu-latest
    needs: docker-build

    steps:
      - uses: actions/checkout@v3

      - name: Download Docker image tar
        uses: actions/download-artifact@v3
        with:
          name: mailsender-image
          path: .

      - name: Copy Docker image tar, .env и db.sqlite3 на сервер
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: |
            mailsender.tar
            .env
            db.sqlite3
          target: "/home/${{ secrets.USERNAME }}/mailsender/"

      - name: Deploy on server via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/${{ secrets.USERNAME }}/mailsender/
            docker load -i mailsender.tar
            docker stop mailsender || true
            docker rm mailsender || true
            docker run -d \
              --name mailsender \
              --env-file .env \
              -v /home/${{ secrets.USERNAME }}/mailsender/db.sqlite3:/app/db.sqlite3 \
              -p 80:8000 \
              mailsender
